module.exports = [
  "api/index",
  {
    "type": "category",
    "label": "Interfaces",
    "items": [
      "api/interfaces/captionlabelprops",
      "api/interfaces/captionprops",
      "api/interfaces/components",
      "api/interfaces/contextbase",
      "api/interfaces/contextmultiple",
      "api/interfaces/contextrange",
      "api/interfaces/contextsingle",
      "api/interfaces/contextuncontrolled",
      "api/interfaces/daycontentprops",
      "api/interfaces/daypickerbase",
      "api/interfaces/daypickermultiple",
      "api/interfaces/daypickerrange",
      "api/interfaces/daypickersingle",
      "api/interfaces/daypickeruncontrolled",
      "api/interfaces/dayprops",
      "api/interfaces/dropdownprops",
      "api/interfaces/monthsdropdownprops",
      "api/interfaces/navigationprops",
      "api/interfaces/rowprops",
      "api/interfaces/selectmultiple",
      "api/interfaces/selectrange",
      "api/interfaces/selectsingle",
      "api/interfaces/selectsingleeventhandler",
      "api/interfaces/styledcomponentprops",
      "api/interfaces/tableprops",
      "api/interfaces/weeknumberprops",
      "api/interfaces/yearsdropdownprops"
    ]
  },
  {
    "type": "category",
    "label": "Type aliases",
    "items": [
      "api/types/captionlayout",
      "api/types/classnames",
      "api/types/contextvalue",
      "api/types/dateafter",
      "api/types/datebefore",
      "api/types/dateformatter",
      "api/types/dateinterval",
      "api/types/daterange",
      "api/types/dayclickeventhandler",
      "api/types/dayfocuseventhandler",
      "api/types/daykeyboardeventhandler",
      "api/types/daylabelformatter",
      "api/types/daymouseeventhandler",
      "api/types/dayofweekmatcher",
      "api/types/daypickerprops",
      "api/types/daypickerproviderprops",
      "api/types/daytoucheventhandler",
      "api/types/focuscontextvalue",
      "api/types/formatters",
      "api/types/labels",
      "api/types/matcher",
      "api/types/modifier",
      "api/types/modifierclassnames",
      "api/types/modifierstatus",
      "api/types/modifierstyles",
      "api/types/modifiers",
      "api/types/modifiersarray",
      "api/types/monthchangeeventhandler",
      "api/types/navbuttonlabelformatter",
      "api/types/navigationcontextvalue",
      "api/types/navigationproviderprops",
      "api/types/selectmultipleeventhandler",
      "api/types/selectrangeeventhandler",
      "api/types/selectionmode",
      "api/types/styledelement",
      "api/types/styles",
      "api/types/useinput",
      "api/types/weeknumberclickeventhandler",
      "api/types/weeknumberformatter",
      "api/types/weeknumberlabelformatter",
      "api/types/weekdaylabelformatter"
    ]
  },
  {
    "type": "category",
    "label": "Variables",
    "items": [
      "api/variables/daypickercontext",
      "api/variables/focuscontext",
      "api/variables/navigationcontext"
    ]
  },
  {
    "type": "category",
    "label": "Functions",
    "items": [
      "api/functions/caption",
      "api/functions/captionlabel",
      "api/functions/day",
      "api/functions/daycontent",
      "api/functions/daypicker",
      "api/functions/daypickerprovider",
      "api/functions/dropdown",
      "api/functions/focusprovider",
      "api/functions/footer",
      "api/functions/head",
      "api/functions/icondropdown",
      "api/functions/iconnext",
      "api/functions/iconprevious",
      "api/functions/monthsdropdown",
      "api/functions/navigation",
      "api/functions/navigationprovider",
      "api/functions/root",
      "api/functions/row",
      "api/functions/selectmultipleprovider",
      "api/functions/selectrangeprovider",
      "api/functions/selectsingleprovider",
      "api/functions/table",
      "api/functions/weeknumber",
      "api/functions/yearsdropdown",
      "api/functions/isarrayofdates",
      "api/functions/isdateaftermatcher",
      "api/functions/isdatebeforematcher",
      "api/functions/isdateinterval",
      "api/functions/isdaterange",
      "api/functions/isdayofweekmatcher",
      "api/functions/issamedatematcher",
      "api/functions/usedaypicker",
      "api/functions/usefocus",
      "api/functions/useinput",
      "api/functions/usemodifiers",
      "api/functions/usenavigation",
      "api/functions/useselectmultiple",
      "api/functions/useselectrange",
      "api/functions/useselectsingle"
    ]
  }
];