module.exports = [
  "api/index",
  {
    "type": "category",
    "label": "Interfaces",
    "items": [
      "api/interfaces/captionhtmlprops",
      "api/interfaces/captionprops",
      "api/interfaces/daycontainerhtmlprops",
      "api/interfaces/dayhtmlprops",
      "api/interfaces/daypickerprops",
      "api/interfaces/dayprops",
      "api/interfaces/daywrapperhtmlprops",
      "api/interfaces/headprops",
      "api/interfaces/monthprops",
      "api/interfaces/navigationhtmlprops",
      "api/interfaces/navigationprops",
      "api/interfaces/rootprops",
      "api/interfaces/weeknumberprops",
      "api/interfaces/weekprops"
    ]
  },
  {
    "type": "category",
    "label": "Type aliases",
    "items": [
      "api/types/captionformatter",
      "api/types/customcomponents",
      "api/types/dayclickeventhandler",
      "api/types/dayformatter",
      "api/types/daykeydowneventhandler",
      "api/types/daykeypresseventhandler",
      "api/types/daykeyupeventhandler",
      "api/types/daymouseentereventhandler",
      "api/types/daypickerclassnames",
      "api/types/daypickerstyles",
      "api/types/daytouchcancelhandler",
      "api/types/daytouchendhandler",
      "api/types/daytouchmoveeventhandler",
      "api/types/daytouchstarteventhandler",
      "api/types/defaultmodifier",
      "api/types/matchafter",
      "api/types/matchbefore",
      "api/types/matchdate",
      "api/types/matchdaysofweek",
      "api/types/matchfromto",
      "api/types/matcher",
      "api/types/modifier",
      "api/types/modifiersclassnames",
      "api/types/modifiersmatchers",
      "api/types/modifiersstatus",
      "api/types/modifiersstyles",
      "api/types/monthchangeeventhandler",
      "api/types/navigationmonths",
      "api/types/uielement",
      "api/types/weeknumberformatter",
      "api/types/weekdaynameformatter"
    ]
  },
  {
    "type": "category",
    "label": "Functions",
    "items": [
      "api/functions/caption",
      "api/functions/day",
      "api/functions/daypicker",
      "api/functions/head",
      "api/functions/month",
      "api/functions/navigation",
      "api/functions/root",
      "api/functions/weeknumber",
      "api/functions/weekrow",
      "api/functions/addtorange",
      "api/functions/getcaptionprops",
      "api/functions/getdayprops",
      "api/functions/getmodifiers",
      "api/functions/getnavigation",
      "api/functions/getnavigationprops",
      "api/functions/useinput",
      "api/functions/userange"
    ]
  }
];