import { useMemo } from 'react';

import { getMDXComponent } from 'mdx-bundler/client/index.js';

import { mdxComponents } from '@/components/mdxComponents';

interface CodeToMdxProps {
  code: string;
}

/** Given a code generated by mdx-bundler, render it as MDX components. */
export function CodeToMdx(props: CodeToMdxProps) {
  const Component = useMemo(() => getMDXComponent(props.code), [props.code]);
  return <Component components={mdxComponents} />;
}
