import type { ApiDefs } from 'scripts';

import { apiDefs } from '@/data/apiDefs';

import { RenderJsx } from './RenderJsx';

/** Given a code generated by mdx-bundler, render it as MDX components. */
export function ApiDescription({ member }: { member: keyof ApiDefs }) {
  const apiDef = apiDefs[member];
  if (!apiDef || !apiDef.shortComment) {
    console.warn(`No API description for ${member}`);
    return <></>;
  }
  return <RenderJsx jsx={apiDef.shortCommentJsx} />;
}
