import type { ApiDefs } from 'scripts';

import { apiDefs } from '@/data/apiDefs';
import { Code, Em, Heading, Popover, Text } from '@radix-ui/themes';

import { RenderJsx } from './RenderJsx';

/** Given a code generated by mdx-bundler, render it as MDX components. */
export function ApiInternalLink({ member }: { member: keyof ApiDefs }) {
  const apiDef = apiDefs[member];
  if (!apiDef) {
    console.warn(
      `ApiInternalLink: member "${member}" not found in the API definitions file`
    );
    return <Code>{member}</Code>;
  }
  return (
    <Popover.Root>
      <Popover.Trigger className="px-1">
        <button>
          <Code
            style={{
              padding: 0,
              background: 'transparent',
              borderRadius: 0,
              borderBottom: '1px dashed currentColor'
            }}
          >
            {member}
          </Code>
        </button>
      </Popover.Trigger>
      <Popover.Content
        side="top"
        align="center"
        style={{ maxWidth: 350 }}
        onOpenAutoFocus={(event) => {
          event.preventDefault();
          (event.currentTarget as HTMLElement)?.focus();
        }}
      >
        <Heading as="h1" size="4">
          <Code>{apiDef.name} </Code>
          <Text size="2" as="span" className="px-1 font-normal">
            <Em>({apiDef.kind.replace('Declaration', '')})</Em>
          </Text>
        </Heading>
        <Text size="1" as="div" className="p-2">
          {apiDef.shortComment && <RenderJsx jsx={apiDef.shortCommentJsx} />}
        </Text>
      </Popover.Content>
    </Popover.Root>
  );
}
