import { getMDXComponent } from "mdx-bundler/client/index.js";

import { mdxComponents as defaultComponents } from "@/components/mdxComponents";
import { MDXComponents } from "mdx/types";

interface RenderJsxProps {
  jsx: string;
  /** Override components used to render the MDX. */
  components?: MDXComponents;
}

/** Given a code generated by mdx-bundler, render it as MDX components. */
export function RenderJsx(props: RenderJsxProps) {
  const { components } = props;
  const Component = getMDXComponent(props.jsx);
  return (
    <Component
      components={{
        ...defaultComponents,
        ...components,
      }}
    />
  );
}
