import { getMDXComponent } from 'mdx-bundler/client/index.js';

import { components } from '@/components/components';
import { MDXComponents } from 'mdx/types';

interface RenderJsxProps {
  jsx: string;
  /** Override components used to render the MDX. */
  components?: MDXComponents;
}

/** Given a code generated by mdx-bundler, render it as MDX components. */
export function RenderJsx(props: RenderJsxProps) {
  const { components: mdxComponents } = props;
  const Component = getMDXComponent(props.jsx);
  return (
    <Component
      components={{
        ...components,
        ...mdxComponents
      }}
    />
  );
}
