import { defaultClassNames } from './defaultClassNames';

test('should match the snapshot', () => {
  expect(defaultClassNames).toMatchInlineSnapshot(`
    {
      "button": "rdp-button",
      "button_reset": "rdp-button_reset",
      "caption": "rdp-caption",
      "caption_between": "rdp-caption_between",
      "caption_dropdowns": "rdp-caption_dropdowns",
      "caption_end": "rdp-caption_end",
      "caption_label": "rdp-caption_label",
      "caption_start": "rdp-caption_start",
      "cell": "rdp-cell",
      "day": "rdp-day",
      "day_disabled": "rdp-day_disabled",
      "day_hidden": "rdp-day_hidden",
      "day_outside": "rdp-day_outside",
      "day_range_end": "rdp-day_range_end",
      "day_range_middle": "rdp-day_range_middle",
      "day_range_start": "rdp-day_range_start",
      "day_selected": "rdp-day_selected",
      "day_today": "rdp-day_today",
      "dropdown": "rdp-dropdown",
      "dropdown_icon": "rdp-dropdown_icon",
      "dropdown_month": "rdp-dropdown_month",
      "dropdown_year": "rdp-dropdown_year",
      "head": "rdp-head",
      "head_cell": "rdp-head_cell",
      "head_row": "rdp-head_row",
      "month": "rdp-month",
      "months": "rdp-months",
      "multiple_months": "rdp-multiple_months",
      "nav": "rdp-nav",
      "nav_button": "rdp-nav_button",
      "nav_button_next": "rdp-nav_button_next",
      "nav_button_previous": "rdp-nav_button_previous",
      "nav_icon": "rdp-nav_icon",
      "root": "rdp",
      "row": "rdp-row",
      "table": "rdp-table",
      "tbody": "rdp-tbody",
      "tfoot": "rdp-tfoot",
      "vhidden": "rdp-vhidden",
      "weeknumber": "rdp-weeknumber",
      "with_weeknumber": "rdp-with_weeknumber",
    }
  `);
});
