test.todo('should apply the class name to the container');
test.todo('should apply the style to the container');
test.todo('should render a select element');
test.todo('should apply the `drop-down` class name to the select element');
test.todo('should apply the `drop-down` to the select element');
test.todo('should render the caption');
test.todo('should apply the `caption_label` class name to the caption');
test.todo('should apply the `caption_label` style to the caption');
test.todo('should render the drop-down icon');
test.todo('should apply the `drop-down_icon` class name to the icon');
test.todo('should apply the `drop-down_icon` style to the icon');
