import { createRequire } from "node:module";
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const require = createRequire(import.meta.url);
const reactSidebar = require("./docs/api/react/typedoc-sidebar.cjs");
const buddhistSidebar = require("./docs/api/buddhist/typedoc-sidebar.cjs");
const ethiopicSidebar = require("./docs/api/ethiopic/typedoc-sidebar.cjs");
const hebrewSidebar = require("./docs/api/hebrew/typedoc-sidebar.cjs");
const hijriSidebar = require("./docs/api/hijri/typedoc-sidebar.cjs");
const persianSidebar = require("./docs/api/persian/typedoc-sidebar.cjs");

const sidebars: SidebarsConfig = {
  docs: [
    "intro",
    "start",
    {
      type: "category",
      label: "Upgrading Guide",
      collapsed: false,
      items: ["upgrading", "upgrading-v8-to-v10"],
    },
    {
      type: "category",
      label: "Customization",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "docs",
        },
      ],
    },
    {
      type: "category",
      label: "Selecting Days",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "selections",
        },
      ],
    },
    {
      type: "category",
      label: "Localization",
      collapsed: false,
      items: [
        "localization/changing-locale",
        "localization/setting-time-zone",
        "localization/iso-and-broadcast",
        "localization/persian",
        "localization/hijri",
        "localization/buddhist",
        "localization/ethiopic",
        "localization/hebrew",
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "guides",
        },
      ],
    },
    {
      type: "category",
      label: "Development",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "development",
        },
      ],
    },
    "changelog",
    "license",
  ],
  api: [
    "api/index",
    {
      type: "category",
      label: "@daypicker/react",
      link: {
        type: "doc",
        id: "api/react/index",
      },
      items: reactSidebar,
    },
    {
      type: "category",
      label: "@daypicker/persian",
      link: {
        type: "doc",
        id: "api/persian/index",
      },
      items: persianSidebar,
    },
    {
      type: "category",
      label: "@daypicker/buddhist",
      link: {
        type: "doc",
        id: "api/buddhist/index",
      },
      items: buddhistSidebar,
    },
    {
      type: "category",
      label: "@daypicker/ethiopic",
      link: {
        type: "doc",
        id: "api/ethiopic/index",
      },
      items: ethiopicSidebar,
    },
    {
      type: "category",
      label: "@daypicker/hebrew",
      link: {
        type: "doc",
        id: "api/hebrew/index",
      },
      items: hebrewSidebar,
    },
    {
      type: "category",
      label: "@daypicker/hijri",
      link: {
        type: "doc",
        id: "api/hijri/index",
      },
      items: hijriSidebar,
    },
  ],
};

export default sidebars;
