import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "." }],
  api: [{ type: "autogenerated", dirName: "." }]
};

export default sidebars;
