declare const styles: {
  readonly "rdp-button_next": string;
  readonly "rdp-button_previous": string;
  readonly "rdp-calendar": string;
  readonly "rdp-caption_label": string;
  readonly "rdp-chevron": string;
  readonly "rdp-chevron_disabled": string;
  readonly "rdp-day": string;
  readonly "rdp-disabled": string;
  readonly "rdp-dropdown": string;
  readonly "rdp-dropdown_nav": string;
  readonly "rdp-dropdown_root": string;
  readonly "rdp-focusable": string;
  readonly "rdp-footer": string;
  readonly "rdp-has_week_numbers": string;
  readonly "rdp-hidden": string;
  readonly "rdp-month": string;
  readonly "rdp-month_caption": string;
  readonly "rdp-month_wrapper": string;
  readonly "rdp-months": string;
  readonly "rdp-months_dropdown": string;
  readonly "rdp-nav": string;
  readonly "rdp-no_weekdays": string;
  readonly "rdp-outside": string;
  readonly "rdp-range_end": string;
  readonly "rdp-range_middle": string;
  readonly "rdp-range_start": string;
  readonly "rdp-selected": string;
  readonly "rdp-today": string;
  readonly "rdp-week": string;
  readonly "rdp-week_number": string;
  readonly "rdp-weekday": string;
  readonly "rdp-weekdays": string;
  readonly "rdp-weeks": string;
  readonly "rdp-years_dropdown": string;
};
export = styles;

