name: react-day-picker

on:
  pull_request:
    branches:
      - main
      - maintenance/v8
  push:
    branches:
      - main
      - maintenance/v8
  workflow_dispatch:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.6.2
      - uses: actions/setup-node@v4
        with:
          node-version: 18.16
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm typecheck

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.6.2
      - uses: actions/setup-node@v4
        with:
          node-version: 18.16
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint --max-warnings=0

  test:
    needs: [lint, typecheck]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.6.2
      - uses: actions/setup-node@v4
        with:
          node-version: 18.16
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.6.2
      - uses: actions/setup-node@v4
        with:
          node-version: 18.16
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: rdp-dist
          path: dist
