name: website

on:
  release:
    types: [published]
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-react-day-picker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: rdp-dist
          path: packages/*/dist

  typecheck-website:
    needs: [build-react-day-picker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - uses: actions/download-artifact@v4
        with:
          name: rdp-dist
          path: packages
      - run: pnpm install --frozen-lockfile
      - run: pnpm -F website typecheck

  build-website:
    needs: [build-react-day-picker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - uses: actions/download-artifact@v4
        with:
          name: rdp-dist
          path: packages
      - run: pnpm install --frozen-lockfile
      - run: pnpm -F website build
      - uses: actions/upload-artifact@v4
        with:
          name: website-build
          path: apps/website/build
